#!/usr/bin/env ruby
system "find . -name '*.rb' | xargs ctags -f .tags"

if File.exist? './Gemfile'
  require 'bundler'
  paths = Bundler.load.specs.map(&:full_gem_path).join(' ')
  system "ctags -R -f .gemtags #{paths}"
end
